### ISSUE TITLE
Enhancement on theme of website and adding Dark-Mode.

### ISSUE THREAD

**Issue by THE-AryanKumar** [Arun9739/Paryatana#95] opened 2022-10-05 13:25 UTC
I want to work on : -

- Improving the Navbar.
- Adding Dark-Mode toggle.
- Making it more Professional.
- Adding proper content and removing Lorem.
- Making the site more Interactive and Responsive 

Can you pls. /assign this issues to me.

**Comment by Arun9739** [comment] 2022-10-05 18:31
@THE-AryanKumar You have the good idea
Except the dark mode you can work on other aspects which you mentioned over there
Plz don't work on dark mode as it has been assigned to someone else

Star the repo ⭐ to showcase your love.

**Comment by Arun9739** [comment] 2022-10-05 18:31
@THE-AryanKumar You have the good idea
Except the dark mode you can work on other aspects which you mentioned over there
Plz don't work on dark mode as it has been assigned to someone else

Star the repo ⭐ to showcase your love.

**Comment by THE-AryanKumar** [comment] 2022-10-06 19:32
@Arun9739 pls review and approve.

**Comment by Arun9739** [comment] 2022-10-14 14:00
@THE-AryanKumar and @AnishKumarGarg Due to inactivity and the issue is proposed by someone else, this issue will be closed.
Plz look for other issues or create new issues.

Star the repo 🌟 to show your support.

**Closed by Arun9739** 2022-10-14 14:00 UTC
Labels: invalid, hacktoberfest
