### ISSUE TITLE
Adding social media links to the card in Contact page

### ISSUE THREAD

**Issue by pandeatul27** [Arun9739/Paryatana#30] opened 2022-10-03 12:57 UTC
**Is your feature request related to a problem? Please describe.**
The Social media buttons on the card of the Contact page don't work.
**Describe the solution you'd like**
I can add links to those buttons.
**Screenshots**
<img width="960" alt="2022-10-03 (1)" src="https://user-images.githubusercontent.com/94844506/193582045-4815c1d7-f1f9-443d-ace3-5113de9ef3ab.png">

**Comment by pandeatul27** [comment] 2022-10-03 12:57
Allow me to work on this issue under hacktoberfest.

**Comment by Arun9739** [comment] 2022-10-03 13:53
@pandeatul27 Thank you for issue.
But the issue is alreday present and has been assigned to someone else.
Create new issue or look for other issues

Show your love by starring the repo 🤩

**Closed** 2022-10-03 13:53 UTC
