### ISSUE TITLE
Adding Favicon

### ISSUE THREAD

**Issue by Rashmisingh-18** [Arun9739/Paryatana#39] opened 2022-10-03 14:58 UTC
**Is your feature request related to a problem? Please describe. **
Want to add favicon

**Describe the solution you'd like**
Favicon help users remember their site while browsing through multiple URLs, so they must be included.

**Screenshots**
https://img.icons8.com/fluency/2x/trave-diary.png

**Comment by mnamesujit** [comment] 2022-10-03 15:03
Hi @Arun9739 I would like to contribute on this issue can you assign me this issue.

**Comment by kishanlalchoudhary** [comment] 2022-10-03 15:26
Hi @Rashmisingh-18  can you assign me this task

**Comment by Joshua-Nweze** [comment] 2022-10-03 17:28
Hi @Arun9739 please assign me this task

**Comment by Arun9739** [comment] 2022-10-03 19:00
@mnamesujit, @Rashmisingh-18, @Joshua-Nweze, @kishanlalchoudhary Thank you for your interest
But the issue is already present and assigned to someone else.
Please create new one or look for other issues.

Show your love by starring the repo 🌟

**Closed by Arun9739** 2022-10-03 19:00 UTC
